### ISSUE TITLE
Preferences does not work in main

### ISSUE THREAD

**Issue by lpatel99** [asfoury/projmag#225] opened 2021-05-20 12:20 UTC

**Comment by arnauds5** [comment] 2021-05-20 12:58
The problem occurs when we modify preferences, maybe the filter is not updated correctly.
When we restart the app, the preferences is loaded as expected, so the problem is not when saving/loading preferences but when we are reloading it maybe.

**Comment by arnauds5** [comment] 2021-06-04 08:42
Fixed in https://github.com/asfoury/projmag/pull/204.

**Closed as completed by arnauds5** 2021-06-04 08:42 UTC
Labels: bug, estimated: 2h
